
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: MedecinModule
        uri: lb://medecin
        predicates:
        - Path=/salle/medecin/**
      - id: PatientModule
        uri: lb://patient
        predicates:
        - Path=/salle/patient/**
      - id: PatientRestClientModule
        uri: lb://PatientRestClient
        predicates:
        - Path=/salle/patient/**
      - id: AdresseModule
        uri: lb://adresse
        predicates:
        - Path=/salle/adresse/**
      - id: HoraireModule
        uri: lb://horaire
        predicates:
        - Path=/salle/horaire/**
      - id: RendezVousModule
        uri: lb://RendezVous
        predicates:
        - Path=/salle/rendezVous/**

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    
        
          
