
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: MedecinModule
        uri: lb://medecin
        predicates:
        - Path=/salle/medecin/**
      - id: PatientModule
        uri: lb://Patient
        predicates:
        - Path=/salle/patient/**
      - id: AdresseModule
        uri: lb://adresse
        predicates:
        - Path=/salle/adresse/**
      - id: HoraireModule
        uri: lb://horaire
        predicates:
        - Path=/salle/horaire/**
      - id: RendezVousModule
        uri: lb://rendezVous
        predicates:
        - Path=/salle/rendezVous/**


    
        
          
