eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
spring:
  application:
    name: applicationEureka
