
  cloud:
    config:
      discovery:
        enabled: true
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/appSallAttBd?createDatabaseIfNotExist=true
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate: 
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
spring:
  application:
    name: application
